# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Users/guo.2154/local/cmake-4.2.3/bin/cmake

# The command to remove a file.
RM = /Users/guo.2154/local/cmake-4.2.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/guo.2154/workspace/projects/ndarray

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/guo.2154/workspace/projects/ndarray

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/Users/guo.2154/local/cmake-4.2.3/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/Users/guo.2154/local/cmake-4.2.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/Users/guo.2154/local/cmake-4.2.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/Users/guo.2154/local/cmake-4.2.3/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/Users/guo.2154/local/cmake-4.2.3/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/Users/guo.2154/local/cmake-4.2.3/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/Users/guo.2154/local/cmake-4.2.3/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/Users/guo.2154/local/cmake-4.2.3/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/Users/guo.2154/local/cmake-4.2.3/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/guo.2154/workspace/projects/ndarray/CMakeFiles /Users/guo.2154/workspace/projects/ndarray//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/guo.2154/workspace/projects/ndarray/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ndarray

# Build rule for target.
ndarray: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ndarray
.PHONY : ndarray

# fast build rule for target.
ndarray/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/ndarray.dir/build.make src/CMakeFiles/ndarray.dir/build
.PHONY : ndarray/fast

#=============================================================================
# Target rules for targets named test_ndarray_core

# Build rule for target.
test_ndarray_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_ndarray_core
.PHONY : test_ndarray_core

# fast build rule for target.
test_ndarray_core/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_ndarray_core.dir/build.make tests/CMakeFiles/test_ndarray_core.dir/build
.PHONY : test_ndarray_core/fast

#=============================================================================
# Target rules for targets named test_ndarray_io

# Build rule for target.
test_ndarray_io: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_ndarray_io
.PHONY : test_ndarray_io

# fast build rule for target.
test_ndarray_io/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_ndarray_io.dir/build.make tests/CMakeFiles/test_ndarray_io.dir/build
.PHONY : test_ndarray_io/fast

#=============================================================================
# Target rules for targets named test_zero_copy

# Build rule for target.
test_zero_copy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_zero_copy
.PHONY : test_zero_copy

# fast build rule for target.
test_zero_copy/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_zero_copy.dir/build.make tests/CMakeFiles/test_zero_copy.dir/build
.PHONY : test_zero_copy/fast

#=============================================================================
# Target rules for targets named test_variable_names

# Build rule for target.
test_variable_names: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_variable_names
.PHONY : test_variable_names

# fast build rule for target.
test_variable_names/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_variable_names.dir/build.make tests/CMakeFiles/test_variable_names.dir/build
.PHONY : test_variable_names/fast

#=============================================================================
# Target rules for targets named test_vector_conversion

# Build rule for target.
test_vector_conversion: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_vector_conversion
.PHONY : test_vector_conversion

# fast build rule for target.
test_vector_conversion/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_vector_conversion.dir/build.make tests/CMakeFiles/test_vector_conversion.dir/build
.PHONY : test_vector_conversion/fast

#=============================================================================
# Target rules for targets named test_fc_ordering

# Build rule for target.
test_fc_ordering: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_fc_ordering
.PHONY : test_fc_ordering

# fast build rule for target.
test_fc_ordering/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_fc_ordering.dir/build.make tests/CMakeFiles/test_fc_ordering.dir/build
.PHONY : test_fc_ordering/fast

#=============================================================================
# Target rules for targets named test_storage_backends

# Build rule for target.
test_storage_backends: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_storage_backends
.PHONY : test_storage_backends

# fast build rule for target.
test_storage_backends/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_storage_backends.dir/build.make tests/CMakeFiles/test_storage_backends.dir/build
.PHONY : test_storage_backends/fast

#=============================================================================
# Target rules for targets named test_storage_streams

# Build rule for target.
test_storage_streams: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_storage_streams
.PHONY : test_storage_streams

# fast build rule for target.
test_storage_streams/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_storage_streams.dir/build.make tests/CMakeFiles/test_storage_streams.dir/build
.PHONY : test_storage_streams/fast

#=============================================================================
# Target rules for targets named test_storage_memory

# Build rule for target.
test_storage_memory: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_storage_memory
.PHONY : test_storage_memory

# fast build rule for target.
test_storage_memory/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_storage_memory.dir/build.make tests/CMakeFiles/test_storage_memory.dir/build
.PHONY : test_storage_memory/fast

#=============================================================================
# Target rules for targets named benchmark_storage

# Build rule for target.
benchmark_storage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 benchmark_storage
.PHONY : benchmark_storage

# fast build rule for target.
benchmark_storage/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/benchmark_storage.dir/build.make tests/CMakeFiles/benchmark_storage.dir/build
.PHONY : benchmark_storage/fast

#=============================================================================
# Target rules for targets named test_distributed_ndarray

# Build rule for target.
test_distributed_ndarray: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_distributed_ndarray
.PHONY : test_distributed_ndarray

# fast build rule for target.
test_distributed_ndarray/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_distributed_ndarray.dir/build.make tests/CMakeFiles/test_distributed_ndarray.dir/build
.PHONY : test_distributed_ndarray/fast

#=============================================================================
# Target rules for targets named test_ghost_exchange

# Build rule for target.
test_ghost_exchange: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_ghost_exchange
.PHONY : test_ghost_exchange

# fast build rule for target.
test_ghost_exchange/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_ghost_exchange.dir/build.make tests/CMakeFiles/test_ghost_exchange.dir/build
.PHONY : test_ghost_exchange/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... benchmark_storage"
	@echo "... ndarray"
	@echo "... test_distributed_ndarray"
	@echo "... test_fc_ordering"
	@echo "... test_ghost_exchange"
	@echo "... test_ndarray_core"
	@echo "... test_ndarray_io"
	@echo "... test_storage_backends"
	@echo "... test_storage_memory"
	@echo "... test_storage_streams"
	@echo "... test_variable_names"
	@echo "... test_vector_conversion"
	@echo "... test_zero_copy"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

